'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'
import Loader from './components/Loader'
import Header from "./common/Header";
import Sidebar from "./common/Sidebar";
import Dashboard from "./Dashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const [loading, setLoading] = useState(false)
  // const pathname = usePathname()

  // useEffect(() => {
  //   setLoading(true)

    // const timeout = setTimeout(() => {
    //   setLoading(false)
    // }, 700) // spinner dikhega 700ms ke liye jab route change hoga

  //   return () => clearTimeout(timeout)
  // }, [pathname])
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {loading && <Loader />}  yahi pe spinner lagega */}

        {children}
      </body>
    </html>
  );
}
